//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmployeesFull
    {
        public int ID { get; set; }

        //[Display(Name = "Employee Name")]
        public string FullName { get; set; }

        //[Display(Name = "Joining Date")]
        public Nullable<System.DateTime> JoiningDate { get; set; }
    }
}
